const Index = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-r from-[#ee9ca7] to-[#ffdde1]">
      <div className="container mx-auto px-4">
        <div className="bg-white rounded-lg shadow-xl p-8 max-w-4xl mx-auto">
          {/* Profile Section */}
          <div className="flex flex-col md:flex-row items-center gap-8 mb-8">
            <img
              src="/pic.png"
              alt="Profile"
              className="w-32 h-32 rounded-full object-cover border-4 border-primary/20"
            />
            <div className="text-center md:text-left">
              <h1 className="text-2xl font-bold mb-2">SHREYA SK</h1>
              <p className="text-gray-600">Registration Number: 233</p>
              <p className="text-gray-600">Department: Computer Science</p>
              <p className="text-gray-600">Section: B</p>
              <p className="text-gray-600">Batch: 2023-24</p>
            </div>
          </div>

          {/* Presentation Title */}
          <div className="text-center mb-8">
            <h2 className="text-2xl font-semibold mb-2">Database Management Systems</h2>
            <h3 className="text-xl text-gray-600 mb-6">Technical Presentation</h3>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="https://www.canva.com/design/DAGd9o6p5qM/view" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center px-4 py-2 bg-primary text-white rounded-md hover:bg-primary/90 transition-colors"
              >
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24">
                  <path d="M2 3h20"></path>
                  <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3"></path>
                  <path d="m7 21 5-5 5 5"></path>
                </svg>
                View Presentation
              </a>
              <button 
                onClick={() => {
                  const reportSection = document.getElementById('report');
                  reportSection?.scrollIntoView({ behavior: 'smooth' });
                }}
                className="inline-flex items-center justify-center px-4 py-2 border border-primary text-primary rounded-md hover:bg-primary/10 transition-colors"
              >
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24">
                  <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"></path>
                  <polyline points="14 2 14 8 20 8"></polyline>
                </svg>
                View Report
              </button>
            </div>
          </div>

          {/* Report Section */}
          <div id="report" className="mt-12">
            <h2 className="text-2xl font-bold mb-6">Seminar Report</h2>
            <div className="prose max-w-none">
              <h3 className="text-xl font-semibold mb-4">Case Study - Leveraging Apple Intelligence Using New Age DBMS</h3>
              <div className="mb-6">
                <p><strong>Name:</strong> S K Shreya</p>
                <p><strong>Branch:</strong> BTech CSE B</p>
                <p><strong>Roll Number:</strong> 1223510233</p>
              </div>

              <h4 className="text-lg font-semibold mb-3">Introduction</h4>
              <p className="mb-4">
                The integration of Database Management Systems (DBMS) in Apple Inc.'s intelligence framework is essential for optimizing data management and enhancing analytical capabilities. This report explores how Apple leverages DBMS technologies to improve operational efficiency, customer relationship management, and business intelligence.
              </p>

              <h4 className="text-lg font-semibold mb-3">DBMS Integration in Apple's Operations</h4>
              <p className="mb-4">
                <strong>Data Processing and Management:</strong> Apple employs advanced DBMS solutions to handle the vast amounts of data generated by its products and services. This includes data from iCloud, Apple Music, and the App Store, which are crucial for understanding user interactions and preferences.
              </p>
              <p className="mb-4">
                <strong>Customer Relationship Management (CRM):</strong> The integration of DBMS allows Apple to maintain detailed customer profiles, enabling personalized marketing strategies. By analyzing customer data, Apple can tailor its offerings to meet specific user needs, enhancing customer satisfaction and loyalty.
              </p>
              <p className="mb-4">
                <strong>Business Intelligence (BI):</strong> Apple utilizes DBMS to support its BI initiatives, providing insights that drive strategic decision-making. The ability to analyze trends and patterns in consumer behavior helps Apple stay ahead of market demands and innovate effectively.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
